[tool.poetry]
name = "sequentialhypothesistestingmodel"
version = "0.1.0"
description = "an implementation of a computational model"
authors = ["Isaac Mierow <mierowir@rose-hulman.edu>"]
license = "MIT"
readme = "README.md"
package-mode = false
# packages = [{include = "sequentialhypothesistestingmodel"}]

[tool.poetry.dependencies]
python = "^3.12"
mkdocs-redirects = "^1.2.3"
mkdocs-minify-plugin = "^0.8.0"
mkdocs-git-revision-date-localized-plugin = "^1.5.1"
mkdocs-awesome-nav = "^3.3.0"
mkdocs-macros-plugin = "^1.5.0"
mkdocs-material = "^9.7.6"
pytest = "^9.0.3"
matplotlib = "^3.10.9"
numpy = "^2.4.4"
pandas = "^3.0.3"
ipykernel = "^7.2.0"

[tool.poetry.group.dev.dependencies]
# ipykernel = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"